### ISSUE TITLE
validate: confusing (wrong?) error message: absolute path is converted to relative?

### ISSUE THREAD

**Issue by cpina** [frictionlessdata/frictionless-prototype-py#18]
```
(venv) carles@pinux:[dev]~/git/frictionless-data-packages/10.5182_zenodo.3836647$ frictionless validate /home/carles/Baixades/create_datapackage_header.csv test.json 
[invalid] ['/home/carles/Baixades/create_datapackage_header.csv', 'test.json']

code            message
--------------  --------------------------------------------------------------------------------------------------
resource-error  The data resource has an error: path "../../../Baixades/create_datapackage_header.csv" is not safe
(venv) carles@pinux:[dev]~/git/frictionless-data-packages/10.5182_zenodo.3836647$ 
```

I'm just testing `frictionless-py` commands. The path in the output was converted from my absolute path and the error message is based on the converted one.

Version: 0.6.1

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by cpina** [comment]
Also, same things for `frictionless describe`:

```
(venv) carles@pinux:[dev]~/git/frictionless-data-packages/10.5182_zenodo.3836647$ frictionless describe /home/carles/Baixades/create_datapackage_header.csv /etc/passwd
[resource-error] The data resource has an error: path "../../../Baixades/create_datapackage_header.csv" is not safe
(venv) carles@pinux:[dev]~/git/frictionless-data-packages/10.5182_zenodo.3836647$ 
```

**Comment by roll** [comment]
Thanks @cpina,

for data packages it uses a concept of a basedir (current working directory by default) so relative paths here are expected. In #27 I'm adding the `trusted` argument to CLI to support unsafe paths for data packages:

```
frictionless describe --trusted /home/roll/projects/goodtables-py/data/valid.csv data/table.csv
```

Although `validate` will fail anyway because it will be a data package with unsafe path

**Comment by roll** [comment]
The PR has closed this issue automatically but let's continue thinking what's behavior is the most user-friendly and at the same time compliant to the Data Package spec
