### ISSUE TITLE
Fix glob pattern in MANIFEST.in

### ISSUE THREAD

**Issue by chris48s** [frictionlessdata/frictionless-prototype-py#6]
# Overview

I tried giving the library a spin and fell at the first hurdle :)

```
$ pip install frictionless
$ frictionless
FileNotFoundError: [Errno 2] No such file or directory: '/home/chris/.virtualenvs/fd-test-fmJcrAQy/lib/python3.6/site-packages/frictionless/assets/profiles/resource/general.json'
```

My  `site-packages/frictionless/assets/profiles/resource` dir only has 

* `geojson.json`
* `inquiry.json`
* `report.json`
* `schema.json`

in it. This is an error with the pattern in `MANIFEST.in` - its not including the subdirs when we build the package. It will be a one-line PR to fix it, but I can't push to a branch in this repo and forking is disabled so I can't submit one :(

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks @chris48s, python packaging is really annoying and I can't set up Travis yet the repo is private. But I'm pushing a commit to fix it hopefully
